---
title: "Word-Embeddings-Emotes"
author: "Michael Puerto"
date: "11/2/2020"
output: html_document
---

## Installing libaries and reading in data. 

```{r}
library(pacman)
p_load(tidyverse,tidytext,tm,lubridate,stringr, text2vec,jsonlite,widyr,quanteda)


file_names = dir("C:/Users/macia/Documents/twitch_clips/October Clips")

G_path = "C:/Users/macia/Documents/twitch_clips/October Clips/"
data = NULL


for(i in file_names){
  L_path = paste(G_path,as.character(i),sep = "")
  data_temp <- fromJSON(as.character(L_path))
  
  chat_temp <- data_temp$comments$message$body
  user_temp <- data_temp$comments$commenter$display_name
  date_temp <- data_temp$comments$commenter$created_at
  streamer_temp <- data_temp$streamer$name
  
  #------------- This was me tyring to pull out the user bages ( Moderator/subcriber etc..)
  # for(i in 1:length(data_temp$comments$message$user_badges)){
  #  id_temp = list(data_temp$comments$message$user_badges[[i]]$`_id`)
  #  id = c(test,id_temp)
    
    
   # }
  
  data_temp = data.frame("body"= chat_temp,"user"=user_temp,"date"=date_temp,"streamer" = streamer_temp, stringsAsFactors = F)
  #assign(paste(i,"data",sep = "_"),data_temp) # this will create new dataframes in the environment
  data = bind_rows(data,data_temp)

}


data %>% glimpse()

```

## Might be good just just to see how many different channels we have. 


```{r}
data %>% group_by(streamer) %>% count(sort = T) %>% top_n(7)

```

```{r}

# Last time I had a hard time combining the text. This seems to work. 

Test <-aggregate(body~streamer, data, paste, collapse = " ")

Test<-Test[1:3,] 


corpus <- corpus(Test,text_field = "body",docid_field = "streamer")
summary(corpus)

```

```{r}

dfm <- dfm(corpus, remove_punct=T)

top = names(topfeatures(dfm,50))
tag_fcm <- fcm(tags)

textplot_network(tag_fcm,min_freq = 0.5, edge_alpha = 0.7, edge_size = .5, vertex_labelsize = 1.5 * rowSums(tag_fcm)/min(rowSums(tag_fcm)))



```

```{r}


tag_fcm <- fcm(dfm)

textplot_network(tag_fcm,min_freeq = 0.7, edge_alpha = 0.7, edge_size = 5)


```

